/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author 1072416842
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemGerenciarAmigos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadastrarFerramentas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuTransação2 = new javax.swing.JMenu();
        jMenuItemEmpréstimo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDevolução = new javax.swing.JMenuItem();
        jMenuRelatório = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuArquivo.setText("Arquivo");
        jMenuArquivo.setMaximumSize(new java.awt.Dimension(60, 32767));
        jMenuArquivo.setMinimumSize(new java.awt.Dimension(60, 22));

        jMenuItemGerenciarAmigos.setText("Gerenciar Amigos");
        jMenuItemGerenciarAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarAmigosActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemGerenciarAmigos);
        jMenuArquivo.add(jSeparator2);

        jMenuItemCadastrarFerramentas.setText("Cadastrar Ferramentas");
        jMenuItemCadastrarFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarFerramentasActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemCadastrarFerramentas);
        jMenuArquivo.add(jSeparator3);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuBar1.add(jMenuArquivo);

        jMenuTransação2.setText("Transação");
        jMenuTransação2.setMaximumSize(new java.awt.Dimension(70, 32767));
        jMenuTransação2.setMinimumSize(new java.awt.Dimension(60, 22));
        jMenuTransação2.setPreferredSize(new java.awt.Dimension(60, 22));

        jMenuItemEmpréstimo.setText("Empréstimo");
        jMenuTransação2.add(jMenuItemEmpréstimo);
        jMenuTransação2.add(jSeparator1);

        jMenuItemDevolução.setText("Devolução");
        jMenuTransação2.add(jMenuItemDevolução);

        jMenuBar1.add(jMenuTransação2);

        jMenuRelatório.setText("Relatório");
        jMenuBar1.add(jMenuRelatório);

        jMenuSobre.setText("Sobre");
        jMenuSobre.setMinimumSize(new java.awt.Dimension(60, 22));
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
//Encerra o programa
System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemGerenciarAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarAmigosActionPerformed
//Instancia a tela de gerenciar de aluno
GerenciaAmigo objeto = new GerenciaAmigo();
objeto.setVisible(true);

    }//GEN-LAST:event_jMenuItemGerenciarAmigosActionPerformed

    private void jMenuItemCadastrarFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarFerramentasActionPerformed
        // Instancia a tela de cadastro de ferramenta
        FrmCadastroFerramenta objeto = new FrmCadastroFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarFerramentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastrarFerramentas;
    private javax.swing.JMenuItem jMenuItemDevolução;
    private javax.swing.JMenuItem jMenuItemEmpréstimo;
    private javax.swing.JMenuItem jMenuItemGerenciarAmigos;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuRelatório;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenu jMenuTransação2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
