/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.util.ArrayList;
import modelo.Amigo;
import modelo.Emprestimo;
import modelo.Ferramenta;

/**
 *
 * @author JUNIOR
 */
public class FrmRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form FrmRelatorio
     */
    public FrmRelatorio() {
        initComponents();
    this.criaRelatorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTARelatorio = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório");

        JTARelatorio.setColumns(20);
        JTARelatorio.setRows(5);
        jScrollPane1.setViewportView(JTARelatorio);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
public void criaRelatorio(){
String string="FERRAMENTAS: \n";
String lista="";
double som=0;
Amigo amg= new Amigo();
Ferramenta frmt= new Ferramenta();
Emprestimo emp= new Emprestimo();
    ArrayList<Amigo> listaAmigo = amg.listaAmigo();
    ArrayList<Ferramenta> listaFerramenta = frmt.listaFerramenta();
    ArrayList<Emprestimo> listaEmprestimo = emp.listaEmprestimo();
    
    for(int i=0;i<listaFerramenta.size();i++){
    lista=lista+  "\n id da Ferramenta: "+listaFerramenta.get(i).getIdFerramenta()+"\n Nome da Ferramenta: "+listaFerramenta.get(i).getNomeFerramenta()+"\n Marca da Ferramenta: "+listaFerramenta.get(i).getMarcaFerramenta()+"\n Custo da Ferramenta: "+listaFerramenta.get(i).getCustoFerramenta()+"\n";
    som += listaFerramenta.get(i).getCustoFerramenta();
    }
    string = string + lista+"\n Custo total das ferramentas: R$"+som+"\n\n AMIGOS: \n";
         lista="";
    for(int i=0;i<listaAmigo.size();i++){
     lista=lista+"\n id do Amigo: "+ listaAmigo.get(i).getIdAmigo()+"\n Nome do amigo: "+listaAmigo.get(i).getNomeAmigo()+"\n Telefone do amigo: "+listaAmigo.get(i).getTelefone()+"\n Numero de emprestimos: "+listaAmigo.get(i).quantidadeEmprestimo(listaAmigo.get(i).getIdAmigo())+"\n possui emprestimo ativo: "+listaAmigo.get(i).possuiEmprestimoAtivo(listaAmigo.get(i).getIdAmigo())+"\n";
    }
    string = string + lista+"\n EMPRESTIMOS: \n";
    lista="";
    for(int i=0;i<listaEmprestimo.size();i++){
        lista=lista+"\n id do Emprestimo: "+listaEmprestimo.get(i).getIDEmprestimo()+"\n Nome do Amigo: "+amg.getNomeAmigo(listaEmprestimo.get(i).getIDAmigo())+"\n Nome da ferramenta: "+frmt.getNomeFerramenta(listaEmprestimo.get(i).getIDFerramenta())+"\n Data de Inicio: "+listaEmprestimo.get(i).getDataEmprestimoInvertido()+"\n Data de Devolucao: "+listaEmprestimo.get(i).getDataDevolucaoInvertido()+"\n";
    }
string = string + lista;
    JTARelatorio.setText(string);
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTARelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
